spring:
  profiles:
    active: prod

taco:
  orders:
    limit: 50000

---
spring:
  profiles: dev

  datasource:
    url: jdbc:h2:mem:tacocloud;MODE=MySQL
    username: a
    password: a
    driver-class-name: org.h2.Driver

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud?createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: pablo-1
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop